<?xml version="1.0"?>
<package>
  <name>sphero_pointing</name>
  <version>0.1.0</version>
  <description>Sphero BOLT controller that follows pointing targets on the paper</description>

  <maintainer email="user@example.com">Mariam Machaidze</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>camera_calibration</build_depend>
  <build_depend>pointing_localization</build_depend>
  <run_depend>rospy</run_depend>
  <run_depend>std_msgs</run_depend>
  <run_depend>geometry_msgs</run_depend>
  <run_depend>sensor_msgs</run_depend>
  <run_depend>camera_calibration</run_depend>
  <run_depend>pointing_localization</run_depend>
  <run_depend>cv_bridge</run_depend>

</package>
